OPENCLOSE_NAME = openclose
OPENCLOSE_VERSION = 1.0
OPENCLOSE_SITE_METHOD = file
OPENCLOSE_SOURCE = $(OPENCLOSE_NAME)-$(OPENCLOSE_VERSION).tar.gz
OPENCLOSE_SITE = ./dl/$(OPENCLOSE_SOURCE)
TEMPALTE_INSTALL_TARGET = YES

define OPENCLOSE_INSTALL_TARGET_CMDS
	$(MAKE) $(LINUX_MAKE_FLAGS) -C $(LINUX_DIR) M=$(@D) modules_install
	$(INSTALL) -m 0755 -D $(@D)/test_$(OPENCLOSE_NAME).sh $(TARGET_DIR)/usr/bin/test_$(OPENCLOSE_NAME).sh
endef

$(eval $(kernel-module))
$(eval $(generic-package))