SYSTEMINFO_NAME = systeminfo
SYSTEMINFO_VERSION = 1.0
SYSTEMINFO_SITE_METHOD = file
SYSTEMINFO_SOURCE = $(SYSTEMINFO_NAME)-$(SYSTEMINFO_VERSION).tar.gz
SYSTEMINFO_SITE = ./dl
SYSTEMINFO_INSTALL_TARGET = YES

define SYSTEMINFO_INSTALL_TARGET_CMDS
	$(MAKE) CC="$(TARGET_CC)" LD="$(TARGET_LD)" -C $(@D) all
endef

$(eval $(generic-package))